
from flask import Flask, render_template_string
import pandas as pd

app = Flask(__name__)

@app.route('/')
def display_stock_data():
    # Read the DataFrame from the Excel file generated by the DCF.py
    dataframe = pd.read_excel('/Users/omarazlan/Financial_analysis_crypto/stock_data.xlsx')
    html_table = dataframe.to_html(index=False)
    return render_template_string(html_table)

if __name__ == '__main__':
    app.run(debug=True)
